[package]
name = "rust_hello_world"
version.workspace = true
documentation.workspace = true
edition = "2024"

[dependencies]
log = { workspace = true }
panic_handler = { workspace = true }

[lib]
crate-type=["staticlib"]
