// Copyright 2024 Accenture.

/* Generated by cbindgen. Do not modify! */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>
#include <ostream>

namespace rustHelloWorld
{

extern "C"
{
uint64_t add(uint64_t left, uint64_t right);

} // extern "C"

} // namespace rustHelloWorld
