// Copyright 2024 Accenture.

/* Generated by cbindgen. Do not modify! */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>
#include <ostream>

namespace rustHelloWorld
{

extern "C"
{
/// Initializes the async rust runtime for the demo task
void init_demo_runtime();

/// This is the entry point which needs to be called to drive the runtime
///
/// ! The runtime must be initialized before calling this function the first time !
void runtime_poll();

} // extern "C"

} // namespace rustHelloWorld
