// Copyright 2024 Accenture.
// clang-format off

#pragma once

/* Generated by cbindgen. Do not modify! */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace rustHelloWorld {

extern "C" {

/// Initializes the async rust runtime for the demo task
void init_rust_runtime(uint8_t context);

/// This is the entry point which needs to be called to drive the runtime
///
/// ! The runtime must be initialized before calling this function the first time !
void runtime_poll(uint8_t context);

}  // extern "C"

}  // namespace rustHelloWorld

// clang-format on
