// Copyright 2024 Accenture.
// clang-format off

#pragma once

/* Generated by cbindgen. Do not modify! */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>
#include "util/logger/LevelInfo.h"

namespace logger {

struct BswLogger;

extern "C" {

extern BswLogger LOGGER;

extern void bsw_cpp_logger_log(uint8_t component_index,
                               ::util::logger::Level level,
                               const char *str);

/// provide information about the loggers to rust
void add_component_info_array(uintptr_t number_of_components,
                              const PlainLoggerMappingInfo *component_info_array);

/// Map all rust logs from one crate to a given logger component
uint8_t map_crate_to_component(const char *crate_, const char *logger_component);

/// The rust logger must be installed after configuration
void install_rust_logging();

}  // extern "C"

}  // namespace logger

// clang-format on
