/* Generated by cbindgen. Do not modify! */

// Copyright 2024 Accenture.

#include "util/logger/LevelInfo.h"

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>
#include <ostream>

namespace logger
{

struct BswLogger;

extern "C"
{
extern BswLogger LOGGER;

extern void
bsw_cpp_logger_log(uint8_t component_index, ::util::logger::Level level, char const* str);

/// provide information about the loggers to rust
void add_component_info_array(
    uintptr_t number_of_components, PlainLoggerMappingInfo const* component_info_array);

/// Map all rust logs from one crate to a given logger component
uint8_t map_crate_to_component(char const* crate_, char const* logger_component);

/// The rust logger must be installed after configuration
void install_rust_logging();

} // extern "C"

} // namespace logger
